### ISSUE TITLE
[Bug] Putty don't start

### ISSUE THREAD

**Issue by Simonz82** [jlesage/docker-putty#12]
### Current Behavior

putty don't start

### Expected Behavior

docker start

### Environment

- OS: DSM 7
- OS version: 7
- CPU: AMD
- Docker version: synology latest
- Device model: synology ds923+
- Browser/OS: synology

### Container creation

docker manager synology

### Container log

```text
Log
[cont-init ] 15-install-pkgs.sh: terminated with error 1.
[cont-init ] 15-install-pkgs.sh: required by: world[https://mirors.alpinelinux.org.
[cont-init ] 15-install-pkgs.sh: https://mirrors.alpinelinux.org (no such package):
[cont-init ] 15-install-pkgs.sh: ERROR: unable to select packages:
[cont-init ] 15-install-pkgs.sh: WARNING: fetching https://mirrors.alpinelinux.org/v3.18/community: No such file or directory
[cont-init ] 15-install-pkgs.sh: fetch https://mirrors.alpinelinux.org/v3.18/community/x86_64/APKINDEX.tar.gz
[cont-init ] 15-install-pkgs.sh: WARNING: fetching https://mirrors.alpinelinux.org/v3.18/main: No such file or directory
[cont-init ] 15-install-pkgs.sh: fetch https://mirrors.alpinelinux.org/v3.18/main/x86_64/APKINDEX.tar.gz
[cont-init ] 15-install-pkgs.sh: installing 'https://mirrors.alpinelinux.org
[cont-init ] 15-install-pkgs.sh: installing requested package(s)..
[cont-init ] 15-install-pkgs.sh: executing
[cont-init ] 15-cjk-font.sh: terminated successfully,
[cont-init ] 15-cjk-font.sh: executing...
[cont-init ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init 10- xdg runtime- dir.s sh: executing...
[cont-init ] 10-x11-unix.sh; terminated successfully
```

### Anything else?

I am not sure if these 2 fields fit these parameters

INSTALL_PACKAGES
PACKAGES_MIRROR

https://mirrors.alpinelinux.org

should I put something else ?
thanks
![2024-08-19_105718](https://github.com/user-attachments/assets/7d3d8f43-e471-4ce8-8a2d-99fd945d8243)

**Comment by jlesage** [comment]
You have to set only variables that are required to fit your needs. You can remove all the ones you don't need.
See for more details https://github.com/jlesage/docker-putty?tab=readme-ov-file#deployment-considerations

**Comment by jlesage** [comment]
You should be able to remove them ?

**Comment by jlesage** [comment]
When you create the container, you can remove all variables with the icon on the left:

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/5dc9f2eb-321e-4c29-ae6d-4167e4263047">

**Comment by Simonz82** [comment]
hi, i resolve, please update your guide for synology:

in progect type this:

version: '3.8'

services:
  putty:
    image: jlesage/putty
    container_name: putty
    ports:
      - "5800:5800"
    volumes:
      - /volume1/docker/appdata/putty:/config:rw
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
      SECURE_CONNECTION: 1
      WEB_AUTHENTICATION: 1
      WEB_AUTHENTICATION_USERNAME: abc
      WEB_AUTHENTICATION_PASSWORD: 123456
      VNC_PASSWORD: 123456

**Comment by jlesage** [comment]
I don't have a guide for Synology, but if you are talking about the Docker compose file, the example provided (https://github.com/jlesage/docker-putty?tab=readme-ov-file#docker-compose-file) is the minimum required to have a functional container. Paths obviously need to be adjusted, since everyone has its own setup.

For Synology, I found that using their UI is easiest way for most people (once you know you have to remove all variables).

**Comment by Simonz82** [comment]
yes exactly. what I wrote, you do it following the user interface, you can publish it as a mini guide for synology.
I wanted to be of help to others ;-)
