### ISSUE TITLE
Error loading XPM image loader: Image type “xpm” is not supported

### ISSUE THREAD

**Issue by mblanco4x4** [jlesage/docker-putty#16]
### Current Behavior

Been running v24.08.1 for quite a while without issue but now with v24.09.1 am getting the below errors. I can rollback and run v24.08.1 just fine. My understanding is that all dependencies are installed at runtime within the docker service itself, correct? Is there anything needing to be passed from the host with the latest version?

Not sure what I'm missing but am sure I'm overlooking something simple. Thanks in advance

### Steps To Reproduce

Attempt to run Latest v24.09.1.

### Environment

- OS: Debian VM

### Container creation

services:

  putty:
    image: jlesage/putty:latest
    container_name: putty
    ports:
      - 5800:5800
    volumes:
      - ./data:/config
    restart: always

### Container log

```text
[app         ] (putty:798): GdkPixbuf-WARNING **: 19:42:20.312: Error loading XPM image loader: Image type “xpm” is not supported
[app         ] (putty:798): GdkPixbuf-CRITICAL **: 19:42:20.312: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed
[app         ] (putty:798): GLib-GObject-CRITICAL **: 19:42:20.312: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[app         ] (putty:798): GdkPixbuf-CRITICAL **: 19:42:20.312: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
[app         ] (putty:798): GdkPixbuf-CRITICAL **: 19:42:20.312: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
[app         ] (putty:798): GdkPixbuf-CRITICAL **: 19:42:20.312: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
```

**Comment by jlesage** [comment]
These messages are "normal" and are not preventing the container from running correctly. What is the issue exactly ?

**Comment by mblanco4x4** [comment]
> These messages are "normal" and are not preventing the container from running correctly. What is the issue exactly ?

Thanks and sorry I should have clarified a bit more. The putty container does run and I am prompted with the initial Putty Config, its when I attempt an ssh connection to any host that the window just goes blank and these errors are logged. When running the previous release v24.08.1 , changing nothing in the config, I can connect without issue and nothing of this sort is logged. Let me dig a bit more.

**Comment by jlesage** [comment]
Ok I see what you mean and I reproduced the issue. I'm working on the fix.

**Comment by mblanco4x4** [comment]
All good now, thanks!
