### ISSUE TITLE
how to we actively disconnect from existing session

### ISSUE THREAD

**Issue by ThermoX360** [jlesage/docker-putty#2]
Hi,

I'm able to connect through a Telnet connection. However, once the connection is established, I can't seem to find a way to disconnect it.  Ctrl-Right-Clicking brings up an (undocumented) drop-down menu, but the "Restart Session" always seems to be grayed out. 

When my connection is established, things seem to work fine (although I'm no expect using these tools).  I just wish they'd be a button on the header where I can disconnect the active connection and bring back the connection menu.

Thanks for the work though.

**Comment by jlesage** [comment]
Currently the easy way is to restart the container.

But I do agree, a better way is needed :)

**Comment by ThermoX360** [comment]
C'est bien ce que je pensais...  ;)

**Comment by jlesage** [comment]
With the latest version (`1.1.0`), there is now a button to restart the session.

**Comment by ThermoX360** [comment]
Thanks for the update!

**Comment by jlesage** [comment]
De rien!
