### ISSUE TITLE
docker-putty crashing on launch (?)

### ISSUE THREAD

**Issue by tmussche** [jlesage/docker-putty#6]
Trying to run putty in docker on Synology DSM 6.
I cannot load the application and in the logs i see the following error:

(putty:889): Gtk-CRITICAL **: 11:19:47.309: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

**Comment by jlesage** [comment]
This message is "normal".  Do you see that the container is stopping itself ?

What do you see when you try to load the app ?  Please share your container configuration (i.e. how you create it) and how you access it.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
